# Catppuccin Macchiato
# https://github.com/catppuccin/catppuccin

name = "Catppuccin Macchiato"
variant = "dark"
background = "#24273a"
foreground = "#cad3f5"

"attribute" = { fg = "yellow" }
"constant" = { fg = "peach" }
"function.builtin" = { fg = "sky" }
"function" = { fg = "blue" }
"keyword" = { fg = "mauve" }
"operator" = { fg = "teal" }
"property" = { fg = "blue" }
"punctuation" = { fg = "overlay2" }
"punctuation.bracket" = { fg = "overlay2" }
"punctuation.delimiter" = { fg = "overlay2" }
"string" = { fg = "green" }
"string.special" = { fg = "red" }
"tag" = { fg = "blue" }
"type" = { fg = "yellow" }
"type.builtin" = { fg = "yellow" }
"variable" = { fg = "text" }
"variable.builtin" = { fg = "red" }
"variable.parameter" = { fg = "peach" }
"comment" = { fg = "overlay0" }
"macro" = { fg = "teal" }
"label" = { fg = "pink" }
"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }
"number" = { fg = "peach" }
"text.literal" = { fg = "text" }
"text.emphasis" = { modifiers = ["italic"] }
"text.strong" = { modifiers = ["bold"] }
"text.uri" = { fg = "blue", modifiers = ["underlined"] }
"text.reference" = { fg = "sky" }
"string.escape" = { fg = "peach" }
"text.title" = { fg = "mauve", modifiers = ["bold"] }
"punctuation.special" = { fg = "pink" }
"text.strikethrough" = { modifiers = ["crossed_out"] }
"spell" = { fg = "text" }

[palette]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
