# Catppuccin Frappé
# https://github.com/catppuccin/catppuccin

name = "Catppuccin Frappé"
variant = "dark"
background = "#303446"
foreground = "#c6d0f5"

"attribute" = { fg = "yellow" }
"constant" = { fg = "peach" }
"function.builtin" = { fg = "sky" }
"function" = { fg = "blue" }
"keyword" = { fg = "mauve" }
"operator" = { fg = "teal" }
"property" = { fg = "blue" }
"punctuation" = { fg = "overlay2" }
"punctuation.bracket" = { fg = "overlay2" }
"punctuation.delimiter" = { fg = "overlay2" }
"string" = { fg = "green" }
"string.special" = { fg = "red" }
"tag" = { fg = "blue" }
"type" = { fg = "yellow" }
"type.builtin" = { fg = "yellow" }
"variable" = { fg = "text" }
"variable.builtin" = { fg = "red" }
"variable.parameter" = { fg = "peach" }
"comment" = { fg = "overlay0" }
"macro" = { fg = "teal" }
"label" = { fg = "pink" }
"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }
"number" = { fg = "peach" }
"text.literal" = { fg = "text" }
"text.emphasis" = { modifiers = ["italic"] }
"text.strong" = { modifiers = ["bold"] }
"text.uri" = { fg = "blue", modifiers = ["underlined"] }
"text.reference" = { fg = "sky" }
"string.escape" = { fg = "peach" }
"text.title" = { fg = "mauve", modifiers = ["bold"] }
"punctuation.special" = { fg = "pink" }
"text.strikethrough" = { modifiers = ["crossed_out"] }
"spell" = { fg = "text" }

[palette]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
