# ef-themes Melissa Dark
# https://protesilaos.com/emacs/ef-themes
# A legible dark honeybee theme with warm colors (yellow, red, green, cyan)

name = "EF Melissa Dark"
variant = "dark"
background = "#352718"
foreground = "#e8e4b1"

"attribute" = { fg = "yellow" }
"constant" = { fg = "cyan" }
"function.builtin" = { fg = "magenta" }
"function" = { fg = "magenta-cooler" }
"keyword" = { fg = "yellow-warmer" }
"operator" = { fg = "fg-alt" }
"property" = { fg = "cyan-warmer" }
"punctuation" = { fg = "fg-dim" }
"punctuation.bracket" = { fg = "fg-dim" }
"punctuation.delimiter" = { fg = "fg-dim" }
"string" = { fg = "green-warmer" }
"string.special" = { fg = "green-cooler" }
"tag" = { fg = "yellow-cooler" }
"type" = { fg = "cyan-cooler" }
"type.builtin" = { fg = "cyan" }
"variable" = { fg = "fg-main" }
"variable.builtin" = { fg = "red-cooler" }
"variable.parameter" = { fg = "magenta-faint" }
"comment" = { fg = "fg-dim", modifiers = ["italic"] }
"macro" = { fg = "magenta-warmer" }
"label" = { fg = "blue-warmer" }
"diff.plus" = { fg = "fg-added" }
"diff.minus" = { fg = "fg-removed" }
"number" = { fg = "blue-cooler" }
"text.literal" = { fg = "fg-main" }
"text.emphasis" = { modifiers = ["italic"] }
"text.strong" = { modifiers = ["bold"] }
"text.uri" = { fg = "blue", modifiers = ["underlined"] }
"text.reference" = { fg = "cyan-warmer" }
"string.escape" = { fg = "yellow-faint" }
"text.title" = { fg = "yellow", modifiers = ["bold"] }
"punctuation.special" = { fg = "red" }
"text.strikethrough" = { modifiers = ["crossed_out"] }
"spell" = { fg = "fg-main" }

[palette]
fg-main = "#e8e4b1"
fg-dim = "#90918a"
fg-alt = "#ccaa70"

red = "#ff7f7f"
red-warmer = "#ff7f4f"
red-cooler = "#ff8f98"
red-faint = "#e89a88"
green = "#6fd560"
green-warmer = "#a0d13a"
green-cooler = "#65d590"
green-faint = "#a0d26f"
yellow = "#e4b53f"
yellow-warmer = "#ffa21f"
yellow-cooler = "#e7a06f"
yellow-faint = "#eab780"
blue = "#57aff6"
blue-warmer = "#98bfff"
blue-cooler = "#62cfef"
blue-faint = "#6ab4ef"
magenta = "#f0aac5"
magenta-warmer = "#fa90aa"
magenta-cooler = "#c6a2fe"
magenta-faint = "#dfcfe0"
cyan = "#6fcad0"
cyan-warmer = "#7fc5df"
cyan-cooler = "#70e0cf"
cyan-faint = "#99bfcf"
fg-added = "#a0e0a0"
fg-removed = "#ffbfbf"
