# GitHub Dark
# https://github.com/primer/github-vscode-theme

name = "GitHub Dark"
variant = "dark"
background = "#0d1117"
foreground = "#c9d1d9"

"attribute" = { fg = "blue" }
"constant" = { fg = "blue" }
"function.builtin" = { fg = "purple" }
"function" = { fg = "purple" }
"keyword" = { fg = "red" }
"operator" = { fg = "red" }
"property" = { fg = "blue" }
"punctuation" = { fg = "fg" }
"punctuation.bracket" = { fg = "fg" }
"punctuation.delimiter" = { fg = "fg" }
"string" = { fg = "lightblue" }
"string.special" = { fg = "red" }
"tag" = { fg = "green" }
"type" = { fg = "orange" }
"type.builtin" = { fg = "orange" }
"variable" = { fg = "fg" }
"variable.builtin" = { fg = "orange" }
"variable.parameter" = { fg = "orange" }
"comment" = { fg = "comment" }
"macro" = { fg = "blue" }
"label" = { fg = "purple" }
"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }
"number" = { fg = "blue" }
"text.literal" = { fg = "fg" }
"text.emphasis" = { modifiers = ["italic"] }
"text.strong" = { modifiers = ["bold"] }
"text.uri" = { fg = "linkblue", modifiers = ["underlined"] }
"text.reference" = { fg = "purple" }
"string.escape" = { fg = "blue" }
"text.title" = { fg = "purple", modifiers = ["bold"] }
"punctuation.special" = { fg = "blue" }
"text.strikethrough" = { modifiers = ["crossed_out"] }
"spell" = { fg = "fg" }

[palette]
bg = "#0d1117"
fg = "#c9d1d9"
comment = "#8b949e"
red = "#ff7b72"
orange = "#ffa657"
green = "#7ee787"
blue = "#79c0ff"
lightblue = "#a5d6ff"
purple = "#d2a8ff"
linkblue = "#58a6ff"
