id = "ssh-config"
name = "SSH Config"
tag = "config"
icon = "mdi:key-chain"
repo = ""
commit = ""
license = ""
inventor = "Tatu Ylönen"
year = 1995
description = "Configuration file format for OpenSSH client settings like hosts, keys, and connection options."
link = "https://man.openbsd.org/ssh_config"
trivia = "SSH was created in 1995 after a password-sniffing attack at Helsinki University of Technology prompted Tatu Ylönen to develop a secure replacement for rlogin."

