id = "erlang"
name = "Erlang"
tag = "code"
icon = "devicon-plain:erlang"
aliases = ["erl"]
repo = ""
commit = ""
license = ""
inventor = "Joe Armstrong, Robert Virding, Mike Williams"
year = 1986
description = "A concurrent, functional language designed for building fault-tolerant distributed systems."
link = "https://en.wikipedia.org/wiki/Erlang_(programming_language)"
trivia = "Erlang was developed at Ericsson for telecom switchesâ€”it achieved 'nine nines' (99.9999999%) uptime in production systems."

