id = "d"
name = "D"
tag = "code"
icon = "mdi:alpha-d-box-outline"
aliases = ["dlang"]
repo = ""
commit = ""
license = ""
inventor = "Walter Bright"
year = 2001
description = "A systems programming language with C-like syntax, designed as a more modern alternative to C++."
link = "https://en.wikipedia.org/wiki/D_(programming_language)"
trivia = "Walter Bright wrote D's first compiler entirely by himselfâ€”he previously created the first native-code C++ compiler for DOS."

