id = "asciidoc"
name = "Asciidoc"
tag = "markup"
icon = "mdi:text-box"
aliases = ["adoc"]
repo = ""
commit = ""
license = ""
inventor = "Stuart Rackham"
year = 2002
description = "A lightweight markup language for writing technical documentation and books."
link = "https://en.wikipedia.org/wiki/AsciiDoc"
trivia = "O'Reilly Media uses AsciiDoc as the source format for many of their technical books."

