id = "dot"
name = "DOT/Graphviz"
tag = "data"
icon = "mdi:graph"
repo = ""
commit = ""
license = ""
inventor = "Stephen North and AT&T Bell Labs"
year = 1991
description = "A graph description language for defining nodes, edges, and graph layouts in Graphviz."
link = "https://en.wikipedia.org/wiki/DOT_(graph_description_language)"
trivia = "Graphviz layout algorithms were developed at AT&T Labs and have been used to visualize everything from compiler internals to social networks."

