id = "cmake"
name = "CMake"
tag = "build"
icon = "devicon-plain:cmake"
repo = ""
commit = ""
license = ""
inventor = "Bill Hoffman"
year = 2000
description = "A cross-platform build system generator for C/C++ projects."
link = "https://en.wikipedia.org/wiki/CMake"
trivia = "CMake was originally developed to support the cross-platform build needs of the Insight Segmentation and Registration Toolkit (ITK)."

