id = "ruby"
name = "Ruby"
tag = "code"
icon = "devicon-plain:ruby"
aliases = ["rb"]
repo = ""
commit = ""
license = ""
inventor = "Yukihiro Matsumoto"
year = 1995
description = "A dynamic, object-oriented language designed for programmer happiness and productivity."
link = "https://en.wikipedia.org/wiki/Ruby_(programming_language)"
trivia = "Matz (Yukihiro Matsumoto) chose the name Ruby as a playful reference to Perlâ€”ruby is a precious stone, like pearl."

